### ISSUE TITLE
getMeta and setMeta types in PM_State.Transaction

### ISSUE THREAD

**Issue by tsnobip** [wearegoat/bs-prosemirror#4]
setMeta and getMeta use the same polymorphic type 'a for the value (as a parameter in setMeta or as a return type in getMeta) as the type of the key (Plugin.t('a) or PluginKey.t('a)) although they're not necessarily related. Plus BuckleScript documentation explicitly warns against annotating a value from JS as a polymorphic option (https://bucklescript.github.io/docs/en/null-undefined-option).
The best option would probably be to use a functor to create a module with setMeta and getMeta with the expected type.
The same polymorphic option issue is faced with OrderedMap and PluginKey.
I can provide a PR if you're interested.

**Comment by alexeygolev** [comment]
@tsnobip Before you go into trouble creating the whole PR would you mind sketching out how would you proposed solution look? I'm not happy with the current solution either. It works but requires some extra annotations.

I think the main point in the recommendation is that "anything can happen in JS" but we'll have to rely on ProseMirror to give us what it promises as that's the lowest API level we get when dealing with FFI. 

In any case I'm very interested in your ideas of a possible solution

**Comment by tsnobip** [comment]
I was thinking about something rather straightforward like that : 

```
 module Meta = {
    module type T = {
      type v;
      let set:
        (
          t,
          ~key: [
                  | `String(string)
                  | `Plugin(Plugin.t('a))
                  | `PluginKey(PluginKey.t('a))
                ],
          ~value: v
        ) =>
        t;
      let get:
        (
          t,
          ~key: [
                  | `String(string)
                  | `Plugin(Plugin.t('a))
                  | `PluginKey(PluginKey.t('a))
                ]
        ) =>
        option(v);
    };

    module Make = (M: {type v;}) : (T with type v := M.v) => {
      type v = M.v;
      [@bs.send]
      external set:
        (
          t,
          ~key: [@bs.unwrap] [
                  | `String(string)
                  | `Plugin(Plugin.t('a))
                  | `PluginKey(PluginKey.t('a))
                ],
          ~value: v
        ) =>
        t =
        "setMeta";

      [@bs.send] [@bs.return nullable]
      external get:
        (
          t,
          ~key: [@bs.unwrap] [
                  | `String(string)
                  | `Plugin(Plugin.t('a))
                  | `PluginKey(PluginKey.t('a))
                ]
        ) =>
        option(v) =
        "getMeta";
    };
  };
```

You would use it that way : 
```
  module MetaString =
    Meta.Make({
      type v = string;
    });

  valueOption = transaction->MetaString.get(~key=`String("myKey"));
```

**Comment by alexeygolev** [comment]
@tsnobip I see how it would work with the ````String``` variant. However that `'a` in the `Plugin.t` is actually the type that we'll get when we do `getMeta`. However with this functor approach we lose this connection.

However if we were to do this:

```
external get:
        (
          t,
          ~key: [@bs.unwrap] [
                  | `String(string)
                  | `Plugin(Plugin.t(v))
                  | `PluginKey(PluginKey.t(v))
                ]
        ) =>
        option(v) =
        "getMeta";
```
we'd have to somehow get the v from the module we create with the functor.

**Comment by tsnobip** [comment]
@alexeygolev well that's actually one of my points, I don't think there's a connection between the type of the Plugin or PluginKey and the type of the value.

**Comment by alexeygolev** [comment]
@tsnobip Sorry, you are absolutely right. Meta data can leterall be anything as it's just data you save to later use when you handle the transaction in your plugin's `apply`. Had to refresh my memory. Your solution makes perfect sense for me then.

You might not need the _destructive substitution_ when you annotate the return type for the functor though.

**Comment by tsnobip** [comment]
@alexeygolev You're right, the destructive substitution is not absolutely needed, but it helps for the type inference, with destructive substitution the return type of `MetaString.get` in my example is `option(string)`, without it would be `option(MetaString.v)` which is less readable I guess. With destructive substitution I could remove the type alias `type v = M.v`and replace `v` annotations with `M.v` but it's probably mainly a matter of presentation. 
I'm really not a specialist of sharing constraints and destructive substitutions, so I might miss some points here.
Should we do the same for OrderedMap and PluginKey that also return polymorphic options?

**Comment by alexeygolev** [comment]
@tsnobip `OrderedMap` is similar to `Js.Dict`. I think we're pretty safe with type variables there (see [Js.Dict implementation](https://github.com/BuckleScript/bucklescript/blob/883da10e9899af6d91b869410022f7dfbb2315f7/jscomp/others/js_dict.ml)). We will have hard time "functorising" it as we don't own the code that creates the values of `OrderedMap` all the time. Some times ProseMirror creates them internally. 
`PluginKey` has a type variable because in ProseMirror docs an instance of `PluginKey` has a `getState` [method](http://prosemirror.net/docs/ref/#state.PluginKey.getState). Type variable is the only way to say that the type of the value returned by this function is the type of our state field. [Here](https://github.com/wearegoat/bs-prosemirror/blob/master/src/PM_State.re#L334) is where they all come together basically
